---
services:
  vector:
    image: timberio/vector:${VECTOR_TAG:-latest-alpine}
    container_name: vector
    hostname: vector
    environment:
      - TZ=${TZ}
    volumes:
      - ${ROOT_DIR}/vector/config:/etc/vector:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${VECTOR_PORT:-8686}:8686
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - diun.enable=true
